modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"
[[mods]]
modId = "endtinker"
version = "1.0.0"
displayName = "endtinker"
authors = "BIAN"
description = '''cs'''
[[dependencies]]
modId = "forge"
mandatory = true
versionRange = "1.20.1-47.4.0"
ordering = "NONE"
side = "BOTH"
[[dependencies]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.20.2)"
ordering = "NONE"
side = "BOTH"

[[dependencies.endtinker]]
modId="tconstruct"
mandatory=true
versionRange="[3.9.2.37,)"
ordering="NONE"
side="BOTH"

[[dependencies.endtinker]]
modId="mantle"
mandatory=true
versionRange="[1.11.43,)"
ordering="NONE"
side="BOTH"

[[dependencies.endtinker]]
modId="jei"
mandatory=false
versionRange="[15.20.0.103,)"
ordering="NONE"
side="BOTH"